// Generated by scripts/generate-migrations-manifest.ts — do not edit by hand.
// Run `nx run @bro/database-app:db:generate` to regenerate.

export type Migration = {
	id: string;
	sql: string;
};
export const migrations: Migration[] = [];
