/**
 * Rewrites src/migrations/manifest.ts from the SQL files drizzle-kit emits.
 *
 * Metro cannot read files off disk at runtime, so migration SQL has to reach
 * the device as bundled JavaScript. Emitting plain TS string literals keeps this
 * working across the package boundary without babel-plugin-inline-import or any
 * Metro `sourceExts` changes in the consuming app.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const drizzleDir = join(packageRoot, "drizzle");
const outputFile = join(packageRoot, "src", "migrations", "manifest.ts");

type JournalEntry = { idx: number; tag: string };
type Journal = { entries?: JournalEntry[] };

async function readJournal(): Promise<JournalEntry[]> {
	try {
		const raw = await readFile(
			join(drizzleDir, "meta", "_journal.json"),
			"utf8",
		);
		const journal = JSON.parse(raw) as Journal;
		return journal.entries ?? [];
	} catch {
		return [];
	}
}

/** Falls back to the directory listing when no journal exists yet. */
async function listMigrationTags(): Promise<string[]> {
	const entries = await readJournal();

	if (entries.length > 0) {
		return [...entries].sort((a, b) => a.idx - b.idx).map((entry) => entry.tag);
	}

	try {
		const files = await readdir(drizzleDir);
		return files
			.filter((file) => file.endsWith(".sql"))
			.sort()
			.map((file) => file.replace(/\.sql$/, ""));
	} catch {
		return [];
	}
}

function toModule(migrations: { tag: string; sql: string }[]): string {
	const header = [
		"// Generated by scripts/generate-migrations-manifest.ts — do not edit by hand.",
		"// Run `nx run @bro/database-app:db:generate` to regenerate.",
		"",
		"export type Migration = {",
		"\tid: string;",
		"\tsql: string;",
		"};",
		"",
	].join("\n");

	if (migrations.length === 0) {
		return `${header}export const migrations: Migration[] = [];\n`;
	}

	const body = migrations
		.map(
			({ tag, sql }) =>
				`\t{\n\t\tid: ${JSON.stringify(tag)},\n\t\tsql: ${JSON.stringify(sql)},\n\t},`,
		)
		.join("\n");

	return `${header}export const migrations: Migration[] = [\n${body}\n];\n`;
}

const tags = await listMigrationTags();
const migrations = await Promise.all(
	tags.map(async (tag) => ({
		tag,
		sql: await readFile(join(drizzleDir, `${tag}.sql`), "utf8"),
	})),
);

await mkdir(dirname(outputFile), { recursive: true });
await writeFile(outputFile, toModule(migrations), "utf8");

console.log(`Wrote ${migrations.length} migration(s) to ${outputFile}`);
