/**
 * Rewrites src/migrations/manifest.ts from the files drizzle-kit emits.
 *
 * Metro cannot read files off disk at runtime, so migration SQL has to reach
 * the device as bundled JavaScript. Emitting plain TS string literals keeps this
 * working across the package boundary without babel-plugin-inline-import or any
 * Metro `sourceExts` changes in the consuming app.
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { PRODUCT_TABLES } from "../src/product-tables";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const drizzleDir = join(packageRoot, "drizzle");
const outputFile = join(packageRoot, "src", "migrations", "manifest.ts");

type JournalEntry = {
	idx: number;
	when: number;
	tag: string;
	breakpoints: boolean;
};
type Journal = { entries?: JournalEntry[] };

async function readJournal(): Promise<JournalEntry[]> {
	try {
		const raw = await readFile(
			join(drizzleDir, "meta", "_journal.json"),
			"utf8",
		);
		const journal = JSON.parse(raw) as Journal;
		return journal.entries ?? [];
	} catch {
		return [];
	}
}

/** Falls back to the directory listing when no journal exists yet. */
async function listMigrationTags(): Promise<string[]> {
	const entries = await readJournal();

	if (entries.length > 0) {
		return [...entries].sort((a, b) => a.idx - b.idx).map((entry) => entry.tag);
	}

	try {
		const files = await readdir(drizzleDir);
		return files
			.filter((file) => file.endsWith(".sql"))
			.sort()
			.map((file) => file.replace(/\.sql$/, ""));
	} catch {
		return [];
	}
}

function toModule(
	entries: readonly JournalEntry[],
	migrations: readonly { index: number; sql: string }[],
): string {
	const header = [
		"// Generated by scripts/generate-migrations-manifest.ts — do not edit by hand.",
		"// Run `nx run @bro/database-app:db:generate` to regenerate.",
		"",
		"",
	].join("\n");

	const journalEntries = entries
		.map(
			(entry) =>
				`\t\t\t{\n\t\t\t\tidx: ${entry.idx},\n\t\t\t\twhen: ${entry.when},\n\t\t\t\ttag: ${JSON.stringify(entry.tag)},\n\t\t\t\tbreakpoints: ${entry.breakpoints},\n\t\t\t},`,
		)
		.join("\n");
	const journal =
		journalEntries.length > 0 ? `[\n${journalEntries}\n\t\t]` : "[]";
	const migrationEntries = migrations
		.map(
			({ index, sql }) =>
				`\t\tm${index.toString().padStart(4, "0")}:\n\t\t\t${JSON.stringify(sql)},`,
		)
		.join("\n");

	return `${header}export const migrations = {\n\tjournal: {\n\t\tentries: ${journal},\n\t},\n\tmigrations: {\n${migrationEntries}\n\t},\n};\n`;
}

const entries = await readJournal();
const tags =
	entries.length > 0
		? entries.map(({ tag }) => tag)
		: await listMigrationTags();
const migrations = await Promise.all(
	tags.map(async (tag, index) => ({
		index,
		sql: await readFile(join(drizzleDir, `${tag}.sql`), "utf8"),
	})),
);

const missingProductTables = PRODUCT_TABLES.filter(
	(table) =>
		!migrations.some(({ sql }) => sql.includes(`CREATE TABLE \`${table}\``)),
);

if (missingProductTables.length > 0) {
	throw new Error(
		`Product tables missing from migrations: ${missingProductTables.join(", ")}`,
	);
}

await mkdir(dirname(outputFile), { recursive: true });
const journalEntries =
	entries.length > 0
		? entries
		: tags.map((tag, idx) => ({
				idx,
				when: idx,
				tag,
				breakpoints: true,
			}));
await writeFile(outputFile, toModule(journalEntries, migrations), "utf8");

console.log(`Wrote ${migrations.length} migration(s) to ${outputFile}`);
